---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: robotremotecontrol-ui
  labels:
    app: robotremotecontrol-ui
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: robotremotecontrol-ui
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: robotremotecontrol-ui
    spec:
      imagePullSecrets:
      - name: image-pull-secret
      containers:
      - name: robotremotecontrol-ui
        image: ghcr.io/pfeigl/robotremotecontrol-ui:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8080
        - name: https
          containerPort: 8443
        envFrom:
        - configMapRef:
            name: robotremotecontrol-ui-env
      terminationGracePeriodSeconds: 180