resources:
- deployment.yaml
- service.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: robotremotecontrol-ui-env
  literals:
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES=true
    - OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY=in_memory
    - ASPNETCORE_FORWARDEDHEADERS_ENABLED=true
    - MQTT_CLIENTID=MyClientId
    - MQTT_USERNAME=MyUsername
    - MQTT_PASSWORD=MyPassword
    - services__mqtt-server__tcp__0=mqtt-server:1883
    - ASPNETCORE_URLS=http://+:8080;

