apiVersion: v1
kind: Secret
metadata:
  name: image-pull-secret
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJjR1psYVdkc09tZG9jRjlNZFhjMU9UZHdVRFJzWW5SSGFIZFlSa1V6U2t4WmVFWlJOMUY2ZUhFMFlUSndSVFU9IiwiZW1haWwiOiJhc3BpcjhAYWthLm1zIn19fQ==
