---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt-server
  labels:
    app: mqtt-server
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: mqtt-server
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mqtt-server
    spec:
      imagePullSecrets:
      - name: image-pull-secret
      containers:
      - name: mqtt-server
        image: ghcr.io/pfeigl/mqtt-server:latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 1883
        envFrom:
        - configMapRef:
            name: mqtt-server-env
      terminationGracePeriodSeconds: 180